---
title: Lucas Neumann
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: lucasneumann.fau@gmail.com
description: 'Lucas Neumann. I juggle research, product design and some code @ Nubank
  Brasil. Co-founder @ projetofeito.

'
baseurl: ''
url: ''
twitter_username: lucasnantonio
github_username: lucasnantonio
google_analytics: UA-72558910-1
markdown: kramdown
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
