---
title: Lucas Neumann
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: lucasneumann.fau@gmail.com
description: 'Lucas Neumann. I juggle research, product design and some code @ Nubank
  Brasil. Co-founder @ projetofeito.'
baseurl: ''
url: 'hrrp://lucasn.com'
twitter_username: lucasnantonio
github_username: lucasnantonio
google_analytics: UA-72558910-1
markdown: kramdown
assets:
  sources:
    - fonts
gems:
- jekyll-feed
- jekyll-assets
exclude:
- Gemfile
- Gemfile.lock
keep_files:
  - .git
  - .gitignore
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
